name: covalent-pycon-2024
dependencies:
  - python=3.10
  - notebook
  - pip:
    - covalent-cloud==0.65.1
    - datasets==2.18.0
    - ipywidgets==8.1.2
    - peft==0.10.0
    - torch==2.2.2
    - transformers==4.39.3
    - trl==0.8.1
variables:
  CC_API_KEY: "paste-your-api-key-here"
